version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: petassistant-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - petassistant-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: petassistant-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - petassistant-network
    restart: unless-stopped

volumes:
  redis-data:
    driver: local

networks:
  petassistant-network:
    driver: bridge